/**
 * Hand-written database types for Phase 1.
 * Extended in each subsequent phase as new tables are added.
 *
 * In a mature project these would be generated by:
 *   npx supabase gen types typescript --project-id <ref> > src/lib/supabase/database.types.ts
 *
 * The Relationships and CompositeTypes fields are required by @supabase/supabase-js
 * for its internal generic type machinery to resolve correctly.
 */

export type Database = {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      users: {
        Row: {
          id: string;
          business_id: string;
          role: "owner" | "staff" | "viewer";
          full_name: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          business_id: string;
          role?: "owner" | "staff" | "viewer";
          full_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          role?: "owner" | "staff" | "viewer";
          full_name?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "users_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_my_business_id: {
        Args: Record<string, never>;
        Returns: string;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

// Convenience row types — imported throughout the codebase
export type BusinessRow = Database["public"]["Tables"]["businesses"]["Row"];
export type UserRow = Database["public"]["Tables"]["users"]["Row"];
